# Generated by Django 4.2.4 on 2024-05-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
