# Generated by Django 4.2.4 on 2024-05-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_mark',
            field=models.IntegerField(default=0),
        ),
    ]
